defaults:
  - model: unet
  - metrics: fid_metric
  - datasets: eval # we do not want to run inference on training data
  - dataloader: example
  - _self_
inferencer:
  device_tensors: ["img", "label"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "eval" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "../Downloads/checkpoint-epoch150.pth" # path to the pretrained model
