defaults:
  - model: unet
  - writer: wandb
  - metrics: fid_metric
  - datasets: train
  - dataloader: example
  - _self_
optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-4
  betas: [0.9, 0.999]
  eps: 1e-8
  weight_decay: 1e-2
lr_scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  T_0: 5
  T_mult: 1
  eta_min: 1e-6
loss_function:
  _target_: src.loss.ExampleLoss
trainer:
  log_step: 50
  n_epochs: 10
  device_tensors: ["img", "label"] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: "cuda:0" # device name or "auto"
  override: True # if True, will override the previous run with the same name
  monitor: "min TEST_FID" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 5 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  seed: 1
